### ISSUE TITLE
Support for Invidious

### ISSUE THREAD

**Issue by TheFrenchGhosty** [po5/mpv_sponsorblock#1]
First, thank you for this port.

However, since I'm using an [Invidious](https://github.com/omarroth/invidious) instance to get my RSS feed I need to rewrite the links to be the youtube one every time, it would be nice if this could support Invidious links too (at least the public instances).

I guess it can be done by using https://instances.invidio.us/ to get the public instances list or by using a wildcard for every links with ```/watch?v=```

**Comment by po5** [comment]
Thanks for the suggestion, I completely forgot about Invidious.
I'll just do the easy thing and not match the youtube domain at all.
Closing this issue, leave a comment if I missed anything.

**Comment by TheFrenchGhosty** [comment]
Thanks a lot for this really quick fix!
