### ISSUE TITLE
Sponsor Database Download Speed

### ISSUE THREAD

**Issue by hl2guide** [po5/mpv_sponsorblock#11]
Manually downloading:
https://sponsor.ajay.app/database.db

is far quicker than the script downloading it as:
sponsorblock.db.tmp

Please try to improve the background download speed of the sponsor database. Is there a limit in place?

**Comment by po5** [comment]
Unless you can demonstrate that this line causes slow requests in general, I'm just gonna assume it works perfectly fine.
https://github.com/po5/mpv_sponsorblock/blob/16610cfed08ed3b178ab3c9e3aa09b3d5cb793db/sponsorblock/shared/sponsorblock.py#L74

**Comment by po5** [comment]
Turns out downloading from the api.sponsor.ajay.app domain is slower than sponsor.ajay.app, Ajay didn't set up Cloudflare properly.

Should be resolved soon, you can set the `server_address` option if you don't want to wait.

**Comment by hl2guide** [comment]
okay thanks po5 👯
