### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by samuelgrf** [po5/mpv_sponsorblock#15]
The project is missing a license, meaning the work is under exclusive copyright by default. This way no one can contribute to the project or distribute it. 
If you are unsure about which license to pick, https://choosealicense.com has concise and easy to understand explanations on what the most common licenses allow and what they don't.

**Comment by po5** [comment]
Sure. Would GPLv3 be compatible with your use of this project in NixOS?

**Comment by samuelgrf** [comment]
Yes it would be, just about any free license would do. It's not strictly necessary, but makes installing the package easier.

**Comment by samuelgrf** [comment]
Thanks.
