### ISSUE TITLE
Statuses in MPV Console

### ISSUE THREAD

**Issue by hl2guide** [po5/mpv_sponsorblock#2]
Please consider adding the display of the status of mpv_sponsorblock in the MPV console.

Statuses that are useful to know:

- [SponsorBlock] %datetime% : Loaded
- [SponsorBlock] %datetime% : Loading Failed
- [SponsorBlock] %datetime% : Sponsor Database Downloading : %progress%
- [SponsorBlock] %datetime% : Sponsor Database Updated
- [SponsorBlock] %datetime% : Sponsor Database Download Failed
- [SponsorBlock] %datetime% : Sponsor Data Loaded

etc..

**Comment by po5** [comment]
There's already a message if the update fails.
I'm not interested in further polluting the console output.

Will leave this open for a week in case you manage to convince me.
