### ISSUE TITLE
Add example of rebinding keys to the readme

### ISSUE THREAD

**Issue by Soundtoxin** [po5/mpv_sponsorblock#20]
I found the instructions to be rather unclear, I hadn't come across the script-binding command before, so I just put in my input.conf something like this:
```
alt+g sponsorblock/set_segment
alt+G sponsorblock/submit_segment
```
which of course results in an error in the mpv console, and left me confused. I got some help from some mpv experts who informed me script-binding was a command to run and that the values from your readme were arguments for it.
In the end I have this, and no more errors:
```
alt+g script-binding sponsorblock/set_segment
alt+G script-binding sponsorblock/submit_segment
```
A subtle but important difference. (I had a key conflict on g with the mpv-gallery-view script, so rebinding the keys had to be done before I could even use this script)

**Comment by po5** [comment]
Good catch, it's hard to know what new users will struggle with when you're already familiar with mpv.
