### ISSUE TITLE
"database update failed, retrying"

### ISSUE THREAD

**Issue by axian32** [po5/mpv_sponsorblock#21]
not working currently 

[](https://imgur.com/dco3gUx)

**Comment by axian32** [comment]
[Image](https://imgur.com/dco3gUx)

**Comment by axian32** [comment]
any idea why this might be happening? i'm using mpv.snad.

**Comment by po5** [comment]
Do you have Python 3 installed and is the sponsorblock_shared directory writable?  
You've provided no information so far so this is not something I can fix or even consider a bug.

**Comment by axian32** [comment]
Sorry for the lack on information! I got it to work by adjusting the input file.

Sep 25, 2020, 4:11 AM by notifications@github.com:
