### ISSUE TITLE
One Menu for all Actions

### ISSUE THREAD

**Issue by mortyobnoxious** [po5/mpv_sponsorblock#26]
Is it possible to use a [menu](https://github.com/ekisu/mpv-webm) like this to do all actions from:

![image](https://user-images.githubusercontent.com/42044258/103299602-f62b5f80-4a0d-11eb-9b16-02f0aad819dd.png)

For example `g` will open this menu:

```
Sponsor Block
1: set segment start 
2: set segment end
c: clear segment boundaries
u: upvote last segment
d: downvote last segment
s: submit
Esc: Close Menu
```

`Submit` will open a new menu similar to existing one:

![image](https://user-images.githubusercontent.com/42044258/103300136-3e974d00-4a0f-11eb-8a0b-6d9cf83b44df.png)

This way users can use just one key to just open menu, other keys would be bound when menu is open and unbound when menu is closed.

Sorry in advance, if this is unnecessary but it would be clean and easy to remember.

**Comment by po5** [comment]
This sounds like something better suited for uosc's menu system https://github.com/darsain/uosc
