### ISSUE TITLE
Fix the Installation section of README.md

### ISSUE THREAD

**Issue by konomikitten** [po5/mpv_sponsorblock#28]
The installation directions for installing don't make sense. Moving the repo's contents into the `scripts` directory will leave you with these two errors:

```
Can't load unknown script: /home/debian/.config/mpv/scripts/LICENSE
Can't load unknown script: /home/debian/.config/mpv/scripts/README.md
```

It would be better to say move the `sponsorblock.lua` file and the `sponsorblock_shared` directory into the `scripts` directory. For anyone new to installing this script it should look something like this:

```
$ tree ~/.config/mpv/scripts/
/home/debian/.config/mpv/scripts/
├── sponsorblock.lua
└── sponsorblock_shared
    ├── main.lua
    └── sponsorblock.py

1 directory, 3 files
```

**Comment by vvirtues** [comment]
This is much better. Some may have also downloaded the ZIP and moved the `mpv_sponsorblock master` or something like that to the `scripts` folder, making it work, but also slower because of the error given for the extra files
