### ISSUE TITLE
Fix for "[sponsorblock] database update failed"

### ISSUE THREAD

**Issue by hl2guide** [po5/mpv_sponsorblock#31]
For me the last time the database update succeeded was: ‎Friday, ‎26 ‎February ‎2021, ‏‎8:33:45 PM

I'm now getting: "[sponsorblock] database update failed"

**Comment by ajayyy** [comment]
The public database is down right now since I switched from sqlite to postgres. I plan to setup something to dump the database soon.

**Comment by hl2guide** [comment]
@po5 Please consider adding "https://sb.ltn.fi/database.db" (offical mirror) as a fallback database URI since "https://sponsor.ajay.app/database.db" is unavailable.

**Comment by ajayyy** [comment]
@hl2guide fyi, that one is "frozen" in the last state of the sqlite db.

**Comment by 07416** [comment]
This mpv_sponsorblock script can't be used at the time at all as-it-is? I don't happen to have the database stored locally.

**Comment by po5** [comment]
Set `local_database=no` to disable this feature for now.
Seems like Ajay won't restore the sqlite db so I may just make this default for the time being.

**Comment by hl2guide** [comment]
Does setting `local_database=no` in the config just make it use the API?

Are there any knockon side effects for setting this?

**Comment by po5** [comment]
Yup. It leaks your watched videos to the sponsorblock server, but `server_fallback` is enabled by default so it's not like much changes at all.

**Comment by ajayyy** [comment]
That's not completely true since it does use fetch with the hash-prefix now

**Comment by tsudoko** [comment]
It's not too hard to adapt the script to use the [new CSV dumps](https://sponsor.ajay.app/database) but it seems like the last entry is the same as the one in the DB file posted in https://github.com/po5/mpv_sponsorblock/issues/31#issuecomment-799765891. I have a [local version](https://github.com/po5/mpv_sponsorblock/compare/master...tsudoko:update-csv) with initial CSV dump support but I'm not sure if there's a point in using it if the dumps aren't up to date.

**Comment by ajayyy** [comment]
Yep, I still haven't got automatic dumps working yet.

**Comment by ajayyy** [comment]
By the way, [this PR](https://github.com/ajayyy/SponsorBlockServer/pull/217) will change the CSV file names dynamically, so I suggest first hitting the JSON endpoint to get the url to pull from.

**Comment by ajayyy** [comment]
The CSV export is now working

**Comment by po5** [comment]
Thanks, I'll look into this when I can. The changing filenames are a bit of a pain, wish there were links that redirect to the latest version of each file but I'll deal with it.

**Comment by ajayyy** [comment]
I now updated it to use redirects. You can now directly request from https://sponsor.ajay.app/database/sponsorTimes.csv, and it will trigger a dump if necessary, and then redirect you to the most recent dump. 

It will not wait for the triggered dump to complete, if that occurred.

**Comment by hl2guide** [comment]
@po5 Any progress to report for this aspect?

**Comment by Whovian9369** [comment]
Happen to have any updates on this?

**Comment by 07416** [comment]
How are you supposed to configure the script now? I cleared the database file recently and only see the `[sponsorblock] database update failed` error in the console:

```
local ON_WINDOWS = package.config:sub(1,1) ~= "/"

local options = {
    server_address = "https://sponsor.ajay.app/database.json",

    python_path = ON_WINDOWS and "python" or "python3",

    -- Categories to fetch
    categories = "sponsor,intro,outro,interaction,selfpromo",

    -- Categories to skip automatically
    skip_categories = "sponsor,intro,outro,interaction,selfpromo",

    -- If true, sponsored segments will only be skipped once
    skip_once = false,

    -- Note that sponsored segments may ocasionally be inaccurate if this is turned off
    -- see https://blog.ajay.app/voting-and-pseudo-randomness-or-sponsorblock-or-youtube-sponsorship-segment-blocker
    local_database = true,

    -- Update database on first run, does nothing if local_database is false
    auto_update = true,

    -- How long to wait between local database updates
    -- Format: "X[d,h,m]", leave blank to update on every mpv run
    auto_update_interval = "6h",
```

Is the line `server_address = "https://sponsor.ajay.app/database.json",` correct and can the `local_database` be disabled?

**Comment by thombelcar** [comment]
I'm also having the same issue.

**Comment by kaistian** [comment]
Since the database format has changed, you can't use local database until someone add the code necessary.
So set `local_database = false,` and `server_address = "https://sponsor.ajay.app",` and it will work.

**Comment by pek0d** [comment]
> Since the database format has changed, you can't use local database until someone add the code necessary.
> So set `local_database = false,` and `server_address = "https://sponsor.ajay.app",` and it will work.

thnx this thing was helpful! And no script is working (macOS 12.1; homebrew)
