### ISSUE TITLE
[feature request] support for skipping intros, outros, self-promotion, subscription reminders

### ISSUE THREAD

**Issue by 07416** [po5/mpv_sponsorblock#36]
https://sponsor.ajay.app/

>also supports skipping other categories, such as intros, outros and reminders to subscribe.

All categories should preferably be available as separate options.

**Comment by po5** [comment]
Already implemented https://github.com/po5/mpv_sponsorblock/blob/29e7b75809107db2bb0c6c6eed0199e063aa75d2/sponsorblock.lua#L13-L17

Feel free to reopen if this is not what you meant.

**Comment by 07416** [comment]
@po5 Sorry, I didn't open the script source. Could you update the readme with clarified instructions to avoid future confusion?

**Comment by po5** [comment]
No.
