### ISSUE TITLE
MPV shows the marker of the sections but doesn't skip the sections

### ISSUE THREAD

**Issue by anishmittal2020** [po5/mpv_sponsorblock#37]
MPV shows the marker of the sections on the "playbar" but doesn't skip the sections. What should I do?

**Comment by po5** [comment]
The sections you see that don't get skipped, are part of the `categories` option but missing from `skip_categories`.

The defaults are as follows:  
`categories = "sponsor,intro,outro,interaction,selfpromo"`
`skip_categories = "sponsor"`

You can remove categories from `categories` to not display them, or add some to `skip_categories` to skip them.  
This script mirrors the SponsorBlock browser extension's behavior of showing all categories and only skipping sponsors by default.
