### ISSUE TITLE
Python was not found

### ISSUE THREAD

**Issue by ObsessedHacker** [po5/mpv_sponsorblock#38]
I Installed:

> python-3.9.6-amd64.exe

And did that: 

> Move this repo's contents into your mpv scripts folder.

On console:

> [sponsorblock] Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I tried uninstalling, restarting, installing again, it doesn't work.
(WIndows 10 Pro 64Bit)

**Comment by super-lurker** [comment]
use this one instead, it doesnt rely on python

https://codeberg.org/jouni/mpv_sponsorblock_minimal

**Comment by po5** [comment]
Keep in mind the fork @super-lurker linked will leak every single video you watch to the SponsorBlock server.

Learn how to install python, it's a google search away.  
If for whatever reason you only have the py launcher or something, you can set the `python_path` script option.

**Comment by ObsessedHacker** [comment]
> Keep in mind the fork @super-lurker linked will leak every single video you watch to the SponsorBlock server.
> 
> Learn how to install python, it's a google search away.
> If for whatever reason you only have the py launcher or something, you can set the `python_path` script option.

By "every single video" you mean only youtube videos, right?
Not local files?

I installed python, but apperently there's more to the install than the normal install file.

**Comment by ObsessedHacker** [comment]
Ok, quick update, I got python installed thank to this:
https://phoenixnap.com/kb/how-to-install-python-3-windows
I needed to run the installer as admin and mark everything to install.
Thank you!

**Comment by po5** [comment]
Yes, only YouTube videos (including local files downloaded with youtube-dl) get leaked by that fork.  
Glad you got it to work.
