### ISSUE TITLE
New category - music_offtopic

### ISSUE THREAD

**Issue by ObsessedHacker** [po5/mpv_sponsorblock#39]
https://github.com/ajayyy/SponsorBlock/wiki/Types#category
There's a new one that isn't included in this script

> music_offtopic

**Comment by po5** [comment]
It's already supported, the behavior matches the browser extension (music segments not shown by default). https://github.com/po5/mpv_sponsorblock/blob/29e7b75809107db2bb0c6c6eed0199e063aa75d2/sponsorblock.lua#L108
