### ISSUE TITLE
[Feature Request] Sponsorblock API should time-out if unreachable

### ISSUE THREAD

**Issue by nicolaasjan** [po5/mpv_sponsorblock#47]
Was unable to watch YouTube video's because the server seems to be down.
See also [this issue](https://github.com/yt-dlp/yt-dlp/issues/1320) at the yt-dlp issue tracker.

Or is this an external issue that has to be handled by youtube-dl/yt-dlp with `--socket-timeout`?

[Edit]
Server seems to be up again.

**Comment by 07416** [comment]
Down again at the time of writing? 

`[sponsorblock] database update failed`

[The maintainer may disagree with the request](https://github.com/po5/mpv_sponsorblock/issues/36#issuecomment-856966766), however. Can the yt-dlp's Sponsorblock capabilities be used when streaming in mpv?

**Comment by nicolaasjan** [comment]
Seems down indeed...

```
ping sponsor.ajay.app
PING sponsor.ajay.app (49.12.210.100) 56(84) bytes of data.

--- sponsor.ajay.app ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7144ms
```

**Comment by nicolaasjan** [comment]
Issue is raised [here](https://github.com/ajayyy/SponsorBlock/issues/1080).

**Comment by nicolaasjan** [comment]
I guess it's solved for now?

ping sponsor.ajay.app
PING sponsor.ajay.app (172.67.148.181) 56(84) bytes of data.
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=1 ttl=55 time=7.76 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=2 ttl=55 time=7.67 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=3 ttl=55 time=9.04 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=4 ttl=55 time=9.17 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=5 ttl=55 time=9.04 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=6 ttl=55 time=8.24 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=7 ttl=55 time=8.84 ms
64 bytes from 172.67.148.181 (172.67.148.181): icmp_seq=8 ttl=55 time=8.70 ms

--- sponsor.ajay.app ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7011ms
rtt min/avg/max/mdev = 7.672/8.561/9.176/0.560 ms
