### ISSUE TITLE
Support for local files downloaded with youtube-dl

### ISSUE THREAD

**Issue by TheFrenchGhosty** [po5/mpv_sponsorblock#5]
By default, [youtube-dl](https://github.com/ytdl-org/youtube-dl) name files ```[Title]-[VIDEOID].[ext]```

Since those stuff are close to standard when using youtube-dl, it would be nice if this script could support it.

My idea would be to have a wildcard for every file that end with ```-ID.mkv``` and ```-ID.mp4```.

I will soon add something similar in my [scripts](https://gitlab.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts) (but I'm waiting to see how you will implement it (if you do).

**Comment by po5** [comment]
I'm hesitant to implement this because it could leak info for files with scene naming.

I'll consider putting it behind an option, but gonna wait to see if you have a better idea.

**Comment by TheFrenchGhosty** [comment]
Yeah you're right...

Well for my scripts I could technically make them use something specific (like ```- ID=[VIDEOID], but the youtube-dl default naming wouldn't work then.
