### ISSUE TITLE
[sponsorblock] database update failed

### ISSUE THREAD

**Issue by Parakovsky** [po5/mpv_sponsorblock#50]
This seems to be popping up constantly in the shell altough the sponsors blocks has been indicated correctly and the server status is online.

**Comment by clonejo** [comment]
This is caused by a 404 at `https://sponsor.ajay.app/database.db`, which has this message:
> Sqlite database has been replaced with csv exports at https://sponsor.ajay.app/database. Sqlite exports might come back soon, but exported at longer intervals.

**Comment by clonejo** [comment]
You can get rid of this error by setting `local_database = false` in the `sponsorblock.lua`.
