### ISSUE TITLE
database update failed

### ISSUE THREAD

**Issue by xavierxross** [po5/mpv_sponsorblock#54]
![image](https://user-images.githubusercontent.com/68507234/170820423-b7dd0e3f-9ec8-47d6-a7b9-b7030506ab4e.png)

**Comment by paindespik** [comment]
same thing here

**Comment by yassin-l** [comment]
i got the same issue too

**Comment by yassin-l** [comment]
You can get rid of this error by changing option `local_database` to false it's by default **true** in the sponsorblock.lua it will look like this `local_database = false`.

**Comment by Soundtoxin** [comment]
Can this option also be set in a script-opts file so that it's not lost when updating? I tried making a file called `sponsorblock.conf` and putting the line in there, but it tells me 
```
sponsorblock: script-opts/sponsorblock.conf:1 unknown key 'local options ', ignoring 
sponsorblock: script-opts/sponsorblock.conf:2 unknown key '    local_database ', ignoring 
```

I tried adding it a few ways with none working so far.

**Comment by christoph-heinrich** [comment]
@Soundtoxin Put the following in `sponsorblock.conf`
```
local_database=no
```

**Comment by Soundtoxin** [comment]
> @Soundtoxin Put the following in `sponsorblock.conf`
> 
> ```
> local_database=no
> ```

Thank you, that worked!
