### ISSUE TITLE
Move configuration to a different file

### ISSUE THREAD

**Issue by rEnr3n** [po5/mpv_sponsorblock#55]
I use `git fetch; git reset --hard origin` to pull the repo (can't use `git pull`). My configuration gets lost whenever I run the commands. I'd appreciate it if the config is decoupled from the application.

**Comment by NicolaSmaniotto** [comment]
You should put your options in `~~/script-opts/sponsorblock.conf` (usually `~~/` expands to `~/.config/mpv/`, see [the manual](https://mpv.io/manual/master/#paths)), without editing the script itself.
