### ISSUE TITLE
`Cannot find main.* [...]` when running mpv

### ISSUE THREAD

**Issue by Witcher01** [po5/mpv_sponsorblock#56]
Full error message:
```
Cannot find main.* for any supported scripting backend in: /home/thomas/.config/mpv/scripts/mpv-sponsorblock-git
```

This issue has been brought up before in #8, saying there has been a fix deployed, but it seems like this is not working for me.

Any guesses?

I installed the version in the AUR with `pkgver=r54.6743bd4`
mpv version: `mpv 0.34.1-dirty`

**Comment by po5** [comment]
Because that's not how you deploy the script.  
Move the *contents* of the repo to your config dir, that is `sponsorblock.lua` and `sponsorblock_shared`.

That AUR PKGBUILD must be outdated.

**Comment by jackmac92** [comment]
A main.lua would make my life easier for installing this via chezmoi externals. 

Is that a bad idea or should I give a PR a shot with my limited lua skills

re: limited lua skills, the evidence I have that a main.lua setup works well is that it works for https://github.com/Ajatt-Tools/videoclip.git
