### ISSUE TITLE
ERROR: Unable to communicate with SponsorBlock API: The read operation timed out

### ISSUE THREAD

**Issue by 07416** [po5/mpv_sponsorblock#57]
There appears to be no issue for this error — seen today with the video `https://www.youtube.com/watch?v=zofBinqC2F4` (if relevant.

```
[ytdl_hook] ERROR: Unable to communicate with SponsorBlock API: The read operation timed out 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.
```

The online database may be unresponsive at the time of writing.

**EDIT**: Sorry, I missed when running `ping` and loading the website:

>This website sponsor.ajay.app/ is currently offline. [Cloudflare's Always Online™](https://www.cloudflare.com/always-online/) shows a snapshot of this web page from the [Internet Archive's Wayback Machine](https://archive.org/web/). 

---

> mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
>  built on UNKNOWN
> FFmpeg library versions:
>    libavutil       57.17.100
>    libavcodec      59.18.100
>    libavformat     59.16.100
>    libswscale      6.4.100
>    libavfilter     8.24.100
>    libswresample   4.3.100
> FFmpeg version: 5.0.1

the current script revision: https://github.com/po5/mpv_sponsorblock/commit/6743bd47d4cfce3ae3d5dd4f587f3193bd4fb9b2

**Comment by po5** [comment]
Such an error would be coming from yt-dlp anyway, unrelated to this script.
