### ISSUE TITLE
[Feature Request] Allow manually skipping categories

### ISSUE THREAD

**Issue by j-ace-svg** [po5/mpv_sponsorblock#63]
I really appreciate being able to manually skip categories in the web extension. Would it be possible to add an option for categories to manually skip and then give some sort of prompt/notice/indicator with the option to skip such a section when it arrises (like the extension)?

**Comment by po5** [comment]
You can empty `skip_categories` and use your regular chapter keybinds.  
The indicator idea is fine but that sounds more suited to be its own script, that can work for anything else e.g. anime openings (:
