### ISSUE TITLE
Errors shown in Command Line - red text

### ISSUE THREAD

**Issue by hl2guide** [po5/mpv_sponsorblock#8]
I'm using the latest version of this repo.

First Run (no sponsorblock.db file):

![first run](https://user-images.githubusercontent.com/17044982/76523782-1ad53b80-64bd-11ea-9bee-293a72b6ccb6.PNG)

Second Run (sponsorblock.db file exists):

![second run](https://user-images.githubusercontent.com/17044982/76523808-26286700-64bd-11ea-9520-39ed819f18ab.PNG)

Files:

![list](https://user-images.githubusercontent.com/17044982/76524209-c67e8b80-64bd-11ea-991a-17eba197ebc6.PNG)

Could you advise about the line: Cannot find main.* ....  ?

**Comment by po5** [comment]
mpv 0.33.0 changed the way scripts are loaded.

I've pushed a backwards compatible fix 958905d, please tell me if that works for you.  
To upgrade, remove the existing `sponsorblock.lua` and the `shared` folder.

**Comment by hl2guide** [comment]
Thanks @po5 

The main.* error seems fixed.

Please consider handling the first run exception for no sponsorblock.db existing yet.

**First Run Currently:**

C:\Users\Dean>mpv "https://www.youtube.com/watch?v=fYOeXytMwoM"
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
AO: [wasapi] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:01 / 00:33:06 (0%) A-V:  0.000 Cache: 14s/3MB
[sponsorblock] Traceback (most recent call last):
[sponsorblock]   File "C:/Portable Software/PortableApps/PortableApps/MPV Video Player/scripts/sponsorblock/shared/sponsorblock.py", line 45, in <module>
[sponsorblock]     c.execute("SELECT startTime, endTime, votes, UUID FROM sponsorTimes WHERE videoID = ? AND shadowHidden = 0 AND votes > -1", (sys.argv[4],))
[sponsorblock] sqlite3.OperationalError: no such table: sponsorTimes

**First Run Suggestion:**

C:\Users\Dean>mpv "https://www.youtube.com/watch?v=fYOeXytMwoM"
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
AO: [wasapi] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:01 / 00:33:06 (0%) A-V:  0.000 Cache: 14s/3MB
[sponsorblock] Trying to download sponsorblock.db (around 33MB)
